<?php 
$reqUrl = $_SERVER['REQUEST_URI'];
$lang['register']['update'] ='Edit Profile'; 
$lang['register']['username'] ='Username<br/><br/><i>Your username will be displayed to the public, and cannot be changed.</i>'; 
$lang['register']['Password'] ='Create Password'; 
$lang['register']['CPassword'] ='Confirm Password'; 
$lang['register']['NewPassword'] ='Change Password'; 
$lang['register']['CNewPassword'] ='Confirm New Password'; 
$lang['register']['pname'] ='Organization / Company Name<font color="red"></font>'; 
$lang['register']['paddress'] ="Please enter the name of the neighborhood and street on which your home is located, or enter detailed directions to your home.<br /><br />
<strong><a href='%padd_ex%' rel='facebox'>View Example</strong></a>"; 
$lang['register']['City'] ='City or Village of Residence'; 
$lang['register']['Country'] ='Country'; 
$lang['register']['email'] ='Email Address<font color="red"></font>'; 
$lang['register']['Website'] ='Website'; 
$lang['register']['d_org'] ='Desription of the organization<font color="red"></font>'; 
$lang['register']['fname'] ='First Name <br/><br/><i>This will not be visible to the public.</i>'; 
$lang['register']['lname'] ='Last Name<br/><br/><i>This will not be visible to the public.</i>'; 
$lang['register']['Photo'] ='Photo<br/>'; 
$lang['register']['d_mailinglist_preferences']='Would you like to receive news and updates regarding Zidisha?'; 
$lang['register']['d_mailinglist_preferences_onloanComment']='Would you like to be notified by email when a comment is posted on one of your loans?';
$lang['register']['d_total_amt'] ='Would you like your loan bids and funded loans to be displayed on your public profile?'; 
$lang['register']['no'] ='No'; 
$lang['register']['yes']='Yes'; 
$lang['register']['A_Yourself'] ='About Yourself (minimum 500 characters)<br/><br/><i>This will display as an introduction of yourself in your loan profile page.  You may choose to describe your family, area where you live, occupation, educational background, why you started a business, what you purchase with the earnings from your business, and any other details that may interest Zidisha lenders in other countries.</i>';
$lang['register']['capacha']='Please enter the security code from the image on the right:<font color="red"></font>'; 
$lang['register']['ppassword'] ='Create Password<font color="red"></font>'; 
$lang['register']['tel_mob_no'] ='Your Mobile Phone Number'; 
$lang['register']['tel_safaricom,'] ='Please enter your Safaricom mobile phone number. <br/><br/><i>Important Note: This must be a Safaricom number registered under your own name. If you provide a number that is not yours, you will not receive a Zidisha loan.</i>'; 
$lang['register']['tel_mtn'] ='Please enter your MTN mobile phone number. <br/><br/><i>Important Note: This must be an MTN number registered under your own name. If you provide a number that is not yours, you will not receive a Zidisha loan.</i>'; 
$lang['register']['aincome'] ='Estimated Annual Income<font color="red"></font>'; 
$lang['register']['bcurrency'] ='Currency<font color="red"></font>'; 
$lang['register']['bdescription'] ='About Your Business or Income Source (minimum 500 characters)<br/><br/>
<i>This will display in your loan profile page to inform potential lenders of the source of income that will be used to repay the loan.  If your source of income is a personal business, you may describe the goods or services your business provides, why there is demand for these goods or services, why your customers prefer your business to the competition, why the business is profitable, the risks your business faces, your typical monthly costs, sales revenue and profits, etc.  If you will not use the loan to invest in a business, please describe the source of income that will allow you to repay the loan.</i>';
$lang['register']['Reset'] ='Reset'; 
$lang['register']['updatebut'] ='Save Changes'; 
$lang['register']['Register']='Register'; 
$lang['register']['Registration']='Registration'; 
$lang['register']['user_type']='Member Type'; 
$lang['register']['Borrower']='Borrower'; 
$lang['register']['Lender']='Lender'; 
$lang['register']['Partner']='Partner'; 
$lang['register']['user_type_dis']='Zidisha borrowers, lenders and partners may create member accounts here.'; 
$lang['register']['borrower_dis']='The borrower is the person who will apply for a loan. <a href="http://www.zidisha.org/editables/Zidisha Guide for Borrowers.pdf">Download the Zidisha Borrower Guide</a>'; 
$lang['register']['Lender_dis']='The lender will bid to finance the borrower.'; 
$lang['register']['Partner_dis']='The partner is a local financial institution or credit bureau that has signed a contract with Zidisha to verify the credit histories of applicants. Only borrowers whose credit histories have been verified by partners are able to post loan applications on the Zidisha website.'; 
$lang['register']['select_type']='Please select the type of account you would like to open.'; 
$lang['register']['t_c']='Terms of Use'; 
$lang['register']['a_a']='Accept Terms of Use'; 
$lang['register']['t_u']='Thank You';  
$lang['register']['member_of']='Thanks for joining us, and welcome!'; 
$lang['register']['bid_on_openloan']='In order to bid on loan applications,';  
$lang['register']['upload_fund_lender_acc']=' please credit your account via the';  
$lang['register']['link_fundupload']='lender funds upload page.<br/><br/>';  
$lang['register']['view_open_loanapplication']='Go to our'; 
$lang['register']['open_loanapplication']='Fundraising Loans';  
$lang['register']['current_borrower_profile']=''; 
$lang['register']['c_borrower_profile']='';  
$lang['register']['postcomment_ques']=' page to browse open loan applications and choose an entrepreneur to fund.';  
$lang['register']['p_contact_us']='Please don\'t hesitate to '; 
$lang['register']['contact_us']='let us know';  
$lang['register']['wd_question_feedback']='if you would like help getting started.  We look forward to hearing from you.  <br/><br/>Best wishes,<br/><br/>Zidisha Team';    
$lang['register']['reg_as_a']='If you have registered as a'; 
$lang['register']['active_info']='your account will be activated'; 
$lang['register']['active_info_p']='as soon as your credit history is verified by a Zidisha partner.'; 
$lang['register']['active_info_a']='as soon as an Administrator activates you.'; 
$lang['register']['confirming']='Your profile has been submitted, and will now be reviewed by Zidisha staff.<br /><br />If any further information is needed, a notification will be sent to your registered email address.  Otherwise, you will be notified by email when a decision has been made on your application to join Zidisha.'; 
$lang['register']['find_partner']='Best wishes,<br/><br/>Zidisha Team'; 
$lang['register']['for']='If you have registered as a'; 
$lang['register']['activate_status']='you will be notified by email once your account is activated.'; 
$lang['register']['wadmin']=' '; 
$lang['register']['for_lend']='Once your account is activated, you may upload funds via PayPal to lend .'; 
$lang['register']['bidfor_lend']='Once funds are uploaded, you will be able to bid to finance businesses at amounts and interest rates of your choosing.';
$lang['register']['bidfor_partner']='Thank you.'; 
$lang['register']['sorry']='SORRY'; 
$lang['register']['error']='error'; 
$lang['register']['nationid']='National ID Number<font color="red"></font>';
$lang['register']['loanhist']='Loan History<font color="red"></font><br/><br/>Please list all loans you currently hold and all loans you have taken in the past.<br/>';
$lang['register']['card_code']='If you have a gift card, please enter the redemption code here';
$lang['register']['invite']='Invite Your Friends';
$lang['register']['enter_emails']="Enter your friends' email addresses here,<br>separated by commas. We’ll send them an<br>invite to Zidisha in your name.";
$lang['register']['invite_msg']='Optional invite message';
$lang['register']['plz_dwnld']='Please download and read the Zidisha Borrower Guide before creating a borrower account. Thanks!';
$lang['register']['import_cont']='Import Your Contacts';
$lang['register']['language']='Language';
$lang['register']['chars_remain']='characters remaining';
$lang['register']['b_fname'] ='First Name'; 
$lang['register']['b_lname'] ='Last Name'; 
$lang['register']['A_Yourself_l'] ='<br/><br/>What would you like other Zidisha members to know about you?<br/><br/>';
$lang['register']['wd_new_loan_app'] ='Would you like to be notified when a borrower you have funded in the past posts a new loan application?';
$lang['register']['join']='Join'; 
$lang['register']['referrer_name']='If you were referred to Zidisha by a current member, please enter his or her username here.'; 
$lang['register']['photo_msg'] ='<br/>Maximum size: 2 MB';
$lang['register']['A_Preferences_l'] ='Account Preferences';
$lang['register']['d_mailinglist_preferences_onloanRepayment_credited']='Would you like to be notified by email when a loan repayment is credited to your account?';
$lang['register']['l_optional']='<br/><i>Optional: if completed this will be displayed in your public profile.</i>';
$lang['register']['mailinglist_preferences_subscribe_newsletter']='Would you like to subscribe to our monthly newsletter?';
$lang['register']['p_emails_notify']="Enter your email addresses here,<br>separated by commas. When a new loan application is sent to you for review, an email notification will go to each of these addresses.";
$lang['register']['community_name_no']="Please enter the name, name of institution, official title and telephone number of a community official (such as a religious or school official) who can provide a personal reference and confirm your residential address.";
$lang['register']['front_national_id']="Please upload a copy of your national identification card.";
$lang['register']['back_national_id']="Please upload a copy of the back of your national identification card.";
$lang['register']['address_proof']="Please download the Recommendation Form below, and upload a completed copy of it here. <br/><br/><i>The Recommendation Form may be completed by either your current Community Leader, or by a different leader of a school, religious institution or other recognized organization in your community.</i><br/><br/>
<strong><a href='images/Recommendation Form.pdf' target='_blank'>Download Recommendation Form</strong></a>";

$lang['register']['legal_declaration']="Please upload a copy of the Legal Contract, which has been completed and signed by you and by a witness.<br/><br/> <a href='images/Legal Contract_EN.pdf' target='_blank'><strong>Download Legal Contract in English</strong></a><br/><br/> <a href='images/Legal Contract.pdf' target='_blank'><strong>Download Legal Contract in Kiswahili</strong></a>";
$lang['register']['referral_code']='If you have a referral code, please enter it here';
$lang['register']['LenderGroup']='Lender (Group or Institution)';
$lang['register']['lgname']='Name of Group or Institution<font color="red"></font>';
$lang['register']['lwebsite']='Website (Optional: if completed this will be displayed in your public profile)';
$lang['register']['photo_logo']='Photo or Logo';
$lang['register']['lgcountry']='Country';
$lang['register']['lgcity']='City or Village of Residence';
$lang['register']['lguserName']='Create Username <font color="red">*</font>';
$lang['register']['borrower_note']="<strong>Note from Zidisha:</strong> Due to the high volume of applications, we are temporarily pausing activation of new borrower accounts. You are still welcome to create an account, but please be aware that it may be some time before we are able to activate it so that you may post a loan application for funding with Zidisha.  We are reviewing and activating all eligible accounts for each country in the order they are received, and current wait time is estimated at up to two months.";
$lang['register']['photo_note']='<br/>Please upload a clear, close, well lit photo of yourself.<br/><br/>
<i>Your loan applications will attract lenders more easily if your photo is smiling and of good quality.</i>';
$lang['register']['Registerlater']='Save and Complete Later'; 
$lang['register']['RegisterComplete']='Submit Final Application'; 
$lang['register']['savechanges']='Save Changes'; 
$lang['register']['ordertojoin']='In order to join Zidisha, you must be able to answer "yes" to the following questions:';
$lang['register']['ordertojoin1']='Do you have a regular source of income that will allow you to repay loans comfortably in monthly installments?';
$lang['register']['ordertojoin2']='Are you currently free of debt (you have paid back any current and past loans that you have taken)?';
$lang['register']['ordertojoin3']='Are you an active internet user, and do you hold a Facebook account with extensive social connections?';
$lang['register']['borrower_behalf'] = 'Applicants may request another person to assist in completing this form, <strong>as long as the applicant participates closely in the application process and has a good understanding of how Zidisha works.</strong> 
<br /><br />If you are posting this application on behalf of another person, we request that this be disclosed to lenders so they may know with whom they are communicating during the loan period. Your response to this question will not have any effect on the approval of this application.
<br /><br />
Are you completing this form for yourself, or on behalf of another person?<br />';


$lang['register']['borrower_behalf1'] = 'I am the applicant and am completing this form for myself.';

$lang['register']['borrower_behalf2'] = 'I am completing this form on behalf of another person.';
$lang['register']['behalf_name'] = 'Name of person completing this form';
$lang['register']['behalf_number'] = 'Telephone number of person completing this form';
$lang['register']['behalf_email'] = 'Email address of person completing this form<br/>(We will send a copy of
all of this applicant\'s account status notifications to this address)';
$lang['register']['behalf_town'] = 'Village or town of residence of person completing this form';
$lang['register']['legal_dec2'] = '<strong>Optional:</strong>  If the second page of the Legal Contract is not included above, please upload it here.';
$lang['register']['addresexample'] = 'I live in Ongata Rongai near Stage One.  From Nairobi Railway Station, take the #125 matatu.  Ask to be dropped in Rongai Stage One.  Take the route from Tumaini Supermarket, straight down.  You will pass a transformer and continue going down.  You will find a place where it looks like a charcoal depot.  There is an M-PESA agent there and a bar called Balozi.  I live behind Balozi, in the house with the blue door.';
$lang['register']['upload_photo']='Upload a photo';
$lang['register']['upload_diffphoto']='Change photo';
$lang['register']['upload_file']='Upload file';
$lang['register']['upload_diff_file']='Upload a different file';
$lang['register']['max_size']='Maximum size:';
$lang['register']['allowed']='Allowed: gif, jpeg, png, pdf</span><br/><span>Maximum size: 2 MB';
$lang['register']['family_contact']='Please enter the name and telephone number of three family members whom we may contact as a reference:';
$lang['register']['family_contact1']='Family Member 1';
$lang['register']['family_contact2']='Family Member 2';
$lang['register']['family_contact3']='Family Member 3';
$lang['register']['neigh_contact']='Please enter the name and telephone number of three neighbors whom we may contact as a reference:';
$lang['register']['neigh_contact1']='Neighbor / Business Associate 1';
$lang['register']['neigh_contact2']='Neighbor / Business Associate 2';
$lang['register']['neigh_contact3']='Neighbor / Business Associate 3';
$lang['register']['home_no']='Please enter your house number or plot number.  If your home is not numbered, please describe how to locate it.';
$lang['register']['lending_institution']='Please enter the name of the lending institution that issued your most recent loan.';
$lang['register']['lending_institution_add']='Please enter the address of the lending institution that issued your most recent loan.';
$lang['register']['lending_institution_phone']='Please enter the telephone number of the lending institution that issued your most recent loan.';
$lang['register']['lending_institution_officer']='Please enter the name of the loan officer who was responsible for your most recent loan.';
$lang['register']['reffered_by']='How did you hear about Zidisha?';
$lang['register']['reffered_member']='Please select the name of the member who referred you to Zidisha:';
$lang['register']['volunteer_mentor']='Please choose one person from this list to serve as your Volunteer Mentor:';
$lang['register']['sign_recomform_name']='Please enter the name, name of institution and official title of a community leader, such as the leader of a local school, religious institution or other community organization, who knows you well and can recommend you for a Zidisha loan.';
$lang['register']['sign_recomform_num']='Please enter the mobile telephone number of the community leader here:';
$lang['register']['contact_type']='Please choose an account authentication method:';
$lang['register']['FB_contact']='Link my Facebook profile';
$lang['register']['tel_contact']='Request telephone contacts to vouch for me';
$lang['register']['fb_instruction']='Please click on the Facebook Connect button to
connect your Facebook account. A link to your public Facebook page will be displayed to lenders in your Zidisha loan profile page.';
$lang['register']['behalf_guideline']='View guidelines for helping others apply';
$lang['register']['endorser']='Please enter the names and email addresses of up to 10 people who know you well and can endorse you for a loan.  <br/><br/><i>In order to be eligible, the endorsers must hold Facebook accounts with extensive social connections, and must not be an existing Zidisha member or endorsing any other Zidisha member.  <br/><br/>When you submit this registration form, an email invite to complete an endorsement form will be sent to each endorser you list here.  Each endorsement received will be published on your Zidisha profile page, and help to attract funding for your loan applications.</i>';
$lang['register']['endorser1_name']='Endorser 1 Name:';
$lang['register']['endorser1_email']='Endorser 1 Email:';
$lang['register']['endorser2_name']='Endorser 2 Name:';
$lang['register']['endorser2_email']='Endorser 2 Email:';
$lang['register']['endorser3_name']='Endorser 3 Name:';
$lang['register']['endorser3_email']='Endorser 3 Email:';
$lang['register']['endorser4_name']='Endorser 4 Name:';
$lang['register']['endorser4_email']='Endorser 4 Email:';
$lang['register']['endorser5_name']='Endorser 5 Name:';
$lang['register']['endorser5_email']='Endorser 5 Email:';
$lang['register']['endorser6_name']='Endorser 6 Name:';
$lang['register']['endorser6_email']='Endorser 6 Email:';
$lang['register']['endorser7_name']='Endorser 7 Name:';
$lang['register']['endorser7_email']='Endorser 7 Email:';
$lang['register']['endorser8_name']='Endorser 8 Name:';
$lang['register']['endorser8_email']='Endorser 8 Email:';
$lang['register']['endorser9_name']='Endorser 9 Name:';
$lang['register']['endorser9_email']='Endorser 9 Email:';
$lang['register']['endorser10_name']='Endorser 10 Name:';
$lang['register']['endorser10_email']='Endorser 10 Email:';
$lang['register']['endorser_save']='Publish Endorsement';
$lang['register']['endorser_instruction']='Please complete this form and click "Publish Endorsement" to publish your endorsement of %bname%\'s application to join the Zidisha online lending organization.<br/><br/>
Please note that your endorsement serves only to confirm the identity and trustworthy reputation of %bname%.  You are not acting as a guarantor for any loans that %bname% may receive from Zidisha.<br/><br/>
When you submit this form, your name, public Facebook profile page and endorsement responses will be displayed online in %bname%\'s loan application page. Your endorsement will help potential lenders feel more confident in lending to %bname%.  We will not display your email address or phone number.';
$lang['register']['endorser_uname']='Create Username';
$lang['register']['endorser_email']='Email Address';
$lang['register']['endorser_tele_no']='Mobile Phone Number';
$lang['register']['borrower_inst']='Please complete each item in this page.  You may save a partially completed form in your member account by clicking "Save and Complete Later."  Once your application is complete, click "Submit Final Application" to send it to Zidisha.';
$lang['register']['facebook_mandatory']="In order to verify your online identity, please click on the 'Facebook Connect' button to link your Facebook account.<br/><br/>
<i>Please ensure that you link your own Facebook account that you have held for a long time and use regularly. A link to your public Facebook page will be displayed to lenders in your Zidisha loan profile page.</i>";
$lang['register']['email_verify']='Your email address has now been confirmed.';
$lang['register']['e_know_brwr']='How do you know %bname%?';
$lang['register']['e_cnfdnt_brwr']='What makes you confident that %bname% can be entrusted with a loan from our community?';
$lang['register']['e_candisplay']='Would you like to display your name, public Facebook profile and endorsement responses online in %bname%\'s loan application page? <br/><br/>Displaying your endorsement will help potential lenders feel more confident in lending to %bname%.  We will not display your email address or phone number.';
$lang['register']['nearest_city']='Please choose the town or village where you are located, or nearest to you:';
$lang['register']['endorser_fb']='In order to verify your identity, please click on the Facebook Connect button to connect your Facebook account.';
$lang['register']['tooltip_mentor']='Volunteer Mentors are Zidisha borrowers or residents of borrowers\' communities, who volunteer their time to assist new members to interact with our website.';
$lang['register']['edited']='Your changes have been saved.';
$lang['register']['partner_commentpost']='Would you like to be notified by email when a comment is posted on the profile of one of the members you activated?';
$lang['register']['additional_verification'] ='Add Verification Credentials'; 
$lang['register']['av_instructions'] ='This page allows you to add verification credentials to your Zidisha profile.<br/><br/>The credentials will be displayed in your profile page, so that lenders will have more confidence in funding your loan applications.  Displaying additional credentials will help your loan applications to be funded more quickly and at lower interest rates.'; 
$lang['register']['step_one'] ='Step One: Link Your Facebook Account'; 
$lang['register']['step_two'] ='Step Two: Upload Your National ID Card'; 
$lang['register']['step_three'] ='Step Three: Add A Community Leader Recommendation'; 
$lang['register']['step_four'] ='Step Four: Invite Your Online Contacts to Endorse You'; 
$lang['register']['step_one_complete'] ='Congratulations! You have completed Step One.'; 
$lang['register']['step_two_complete'] ='Congratulations! You have completed Step Two.'; 
$lang['register']['step_three_complete'] ='Congratulations! You have completed Step Three.'; 
$lang['register']['cl_name'] ='Your Community Leader Name';
$lang['register']['cl_tel'] ='Your Community Leader Telephone Number';
$lang['register']['create_account'] ='Create Account';
$lang['register']['contact_info'] ='Contact Information';
$lang['register']['references'] ='References';
$lang['register']['public_profile'] ='Your Public Profile';
?>