<?php
$lang['about']['desc']='<b>Tentang Kami</b><br />
<p>Zidisha, Inc. adalah sebuah  501(c)(3) organisasi nirlaba berbentuk badan hukum di Virginia, USA.<p/><p/><p/>
<br /><b>Tim Zidisha</b>
<p>JULIA KURNIA, Direktur</p>
<p>Julia bekerja untuk menghubungkan pengusaha-pengusaha di negara-negara miskin dengan pinjaman peer-to-peer internasional yang dimulai tahun 2006, ketika beliau menemukan the Senegal Ecovillage Microfinance Fund,  lembaga microfinance dunia pertama yang dibangun dengan modal yg dihasilkan melalui pinjaman P2P. Kemudian dia menghabiskan empat bulan di Kenya melakukan penelitian mengenai bagaimana cara untuk memadukan mobile banking dengan microfinance untuk MyC4, sebuah servis pinjaman microfinance P2P yang berada di Denmark. Pengalaman-pengalaman inilah yang merupakan dasar dari awal terbentuknya Zidisha pada tahun 2009. Julia bekerja sebagai analis Portfolio (Portfolio Analyst) di United States African Development Foundation in Washington, DC, dan memiliki gelar Master di Ekonomi Internasional (International Economics). Anda dapat menghubi beliau di <a href=\'mailto:julia@zidisha.org\'>julia@zidisha.org</a>.</p></p><br />

<p>ALLEN TALBERT, Manajer Hubungan Klien Senegal   
  <a href=\'http://dakaraducoeur.tumblr.com/\'>Lihat Laman Blog</a>  </p>
<p>Allen pada saat ini terdaftar sebagai murid S2 di Poitiers, Perancis dimana dia belajar Migrasi dan Pembangunan (Migration and Development). Program ini, bersamaan dengan ketertarikannya di microcredit, telah menginspirasi dia untuk menjadi Manajer Hubungan Klien di Dakar. Dia mempertimbangkan microfinance sebagai sebuah wakil perubahan dan strategi yang effisien sebagai tanggapan dari kurangnya peranan lembaga, seperti perbankan, di daerah Selatan, yang dapat menjamin pembiayaan peminjaman pengusaha-pengusaha yang kurang mampu yang diperlukan untuk membantu mereka. Di masa yang akan datang dia ingin memenuhi potensi microcredit dengan menyambungkan mitra-mitra keuangan financial partners di Utara dengan organisasi-organisasi daerah di daerah Selatan, untuk mendukung pembangunan pertanian dan perlawanan terhadap kedaulatan pangan. Dia dapat dihubungi melalui <a href=\'mailto:allen@zidisha.org\'>allen@zidisha.org</a>.</p></p><br />


<p>IZAAK BRUCE, Perhubungan Kolega</p>
<p>Izaak adalah murid tahun kedua di Universitas Amerika di Washington DC, dengan jurusan di Studi Internasional (International Studies) dan memiliki minor Arab dan Bisnis Internasional (Arabic and International Business).  Dia merupakan salah satu anggota dayung AU Crew dan menyukai membaca dan tamasya.  Tahun depan dia ingin belajar di Yordania sembari menyelesaikan minor nya.  Izaak terutama fokus pada Timur Tengah dan dampak pada kebijakan luar negeri dan ekonomi Amerika Serikat.  Pada tahun 2010 dia bekerja magang sebagai peneliti dengan Fondasi Karibia (Caribbean Foundation) dan belajar mengenai dampak peraturan reasuransi pada perekonomian Karibia.  Izaak berharap untuk mengembangkan karirnya ke arah yang dapat membuat dia menjelajahi ketertarikannya di Timur Tengah ekonomi, dan kebijakan luar negeri. Izaak dapat dihubungi melalui <a href=\'mailto:izaak@zidisha.org\'>izaak@zidisha.org</a>.</p></p><br />

<p>LAUREN ROSENBAUM, Penasihat   
  <a href=\'http://ikosawa.wordpress.com/\'>Lihat Laman Blog</a> </p>
<p>Lauren bertindak sebagai Manajer Hubungan Klien di Kenya yang pertama pada musim panas 2010, serta sebagai Perhubungan Kolega pada musim gugur2010.  Dia sekarang sedang menjalani tahun keempatnya di Dartmouth College, dimana dia belajar Hubungan Internasional dan Perbandingan Politik dan menulis untuk koran kampus nya. Pada musim dingin tahun 2010, dia menerima dana dari Dickey Center for International Understanding untuk bekerja magang di bidang komunikasi di International Crops Research Institute for the Semi-Arid Tropics (ICRISAT) yang terletak di Nairobi, Kenya. karya nya selama bekerja di ICRISAT termasuk merancang bahan pendidikan, rapat dengan pengolah makanan, pedagang gandum, dan wakil dari Kenya Bureau of Standards (KEBS) di Nairobi, dan memimpin loka karya dengan grup petani setempat di daerah pedesaan sebelah selatan Kenya. Kerjanya bersama ICRISAT membulatkan ketertarikannya di pembangunan internasional dan keinginannya untuk bekerja dengan penduduk pedesaaan di daerah Kenya. Setelah kepulangannya ke Dartmouth di musim semi, dia mengajukan aplikasi atas pembiayaan dana untuk kembali ke Kenya sebagai Manajer Hubungan Klien Zidisha di Kenya dan menerima dana dari Darmouth\'s Institute of Security, Technology, and Security.
Anda dapet melihat laman blog nya <a href=\'http://ikosawa.wordpress.com/\'>weblog</a>  untuk mengetahui lebih mengenai karyanya bersama pengusaha-pengusaha Zidisha di pedesaan Kenya, atau menghubungi dia langsung di <a href=\'mailto:lauren@zidisha.org\'>lauren@zidisha.org</a>.</p></p><br />

<p>JOHN FAY, Komisaris</p>
<p>John telah terlibat dalam microfinance di Africa sejak 2004, ketika dia mulai mengembangkan pendahulu organisasi ini yang menjadi <a href=\'http://www.sem-fund.org\'>The Senegal Ecovillage Microfinance Fund</a> di tahun 2006, ditemukan bersama Nan Guslander, Julia Blue Kurnia dan Boubacar Sarr. John berperan sebagai ketua dewan SEM 501(c)(3) dan direktur untuk SEM, bertumpu pada strategi dan pengembangan kemitraan. John sedang berada di Cape Town, Afrika Selatan, dimana dia sedang mengejar gelar Doktor di Universitas Cape Town Graduate School of Business, memusatkan pada insentif keuangan dan mekanisme yang diperlukan Afrika untuk mengatasi masalah mitigasi perbuahan cuaca dan adaptasi. John juga bekerja separuh waktu untuk msebagai konsultan di konsultan internasional: Cardno Emerging Markets, bekerja untuk menuntun inisiatif perubahan cuaca mereka. Sebelumnya John telah bekerja di Cigna Healthcare, bank penanaman modal FBR dan Emerging Markets Group, Serta merupakan seorang pemain lacrosse profesionalselama 6 tahun. Selama bekerja di SEM Fund dan Emerging Markets Group, dia diberi Penghargaan Society in International Development\'s Truman Award pada tahun 2006. Dia lulus bergelar BA dengan jurusan History dari Universitas Duke dan menerima gelar MBA dari Cornell University\'s Johnson School. John dapat dihubungi di <a href=\'mailto:john@sem-fund.org\'>john@sem-fund.org</a>.</p></p> <br />

<p>DIANNE SCENT, Komisaris</p>
<p>Dianne adalah seorang editor lepas di Bagian timur Tennessee, dimana dia menyukai pegunungan-pegunungan di rumah barunya. Selama 20 tahun dia berkarier di bidang penerbitan termasuk bekerja sebagai redaktur hukun dan pendidikan untuk Wiley, Cambridge University Press, dan Transaction Publishers, serta Christian publisher Zondervan. Dia lulus dari Hanover College dengan gelar BA di Bahasa Inggris. Keterlibatannya di microfinance berakar dari Mikha 6:8 \'Hai manusia, telah diberitahukan kepadamu apa yang baik. Dan apakah yang dituntut TUHAN dari padamu: selain berlaku adil, mencintai kesetiaan, dan hidup dengan rendah hati di hadapan Allahmu?\' Inspirasi nya termasuk Ibu Theresa dan Shane Claiborne. Anda dapat menghubungi Diana di <a href=\'mailto:dscent@mindspring.com\'>dscent@mindspring.com</a>.</p></p><br />

<p>PRANJAL SRIVASTAVA, Chief Executive Officer, <a href=\'http://www.CodeFire.in\'>CodeFire Technologies Pvt. Ltd.</a></p>
<p>CodeFire Technologies adalah sebuah perusahaan software yang berada di India. Kami senang mengembangkan aplikasi berdasarkan-web yang menantang dan ini yang menyebabkan kami menjalin kerja sama dengan  Zidisha.org. kita menghargai jenis mimbar yang Zidisha.org sedang buat dan pelihara, dan mengerti bahwa ini merupakan sarana yang amat baik untuk mendukung pengusaha-pengusaha baru dan menyediakan mereka modal yang dperlukan untuk mengembangkan usaha mereka ke level selanjutnya. CodeFire Technologies Pvt. Ltd., dengan kemampuan teknik nya di berbagai hal yang berbeda telah mengembangkan tekonologi untuk menyediakan mimbar yang kuat untuk Zidisha.org. Sesuai dengan Pranjal Srivastava, CEO CodeFire Technologies, \'Kita berkomitmen untuk memberikan teknologi terbaik kepada Zidisha.org untuk memberi servis pada level tertinggi dan kepuasan di lingkungan peer-to-peer microfinancing. Kita bangga untuk bermitra dengan Zidisha.org dlaam hal teknologi dan mendukung ikhtiarnya.\' Anda dapat menghubungi Pranjal di <a href=\'mailto:pranjal@codefire.in\'>pranjal@codefire.in</a>. </p></p>';
?>