<?php
$lang['legal_info']['desc']='<br/><b>Persyaratan Penggunaan</b>
<p>Melalui website kami, www.zidisha.org, Zidisha mencocokkan pemberi pinjaman (yang selanjutnya akan disebut sebagai pendana) dengan calon peminjam, yang merupakan pengusaha-pengusaha kecil di Negara-negara berkembang. Zidisha bekerja untuk memberi akses pendanaan usaha (usaha dengan biaya yang terjangkau) kepada pengusaha-pengusaha yang tidak memiliki kesempatan, dengan menyediakan informasi mengenai usaha peminjam dan sejarah piutang peminjam supaya dapat memberikan pendana pilihan-pilihan mengenai pengusaha mana yang akan menerima dana yang akan mereka berikan. </p>
<p>Pinjaman-pinjaman yang ditawarkan melalui Zidisha adalah tanpa jaminan dan seringkali dianggap beresiko tinggi oleh lembaga-lembaga keuangan tradisional. Sebagai tambahan, Zidisha tidak berkewajiban untuk mengembalikan seluruh atau sebagian dana yang diberikan oleh pemberi pinjaman. Maka dari itu, dalam berpartisipasi menyediakan dana melalui Zidisha adalah dianggap sebagai usaha derma daripada sebuah kegiatan investasi. Pengguna-pengguna website harus memberikan pinjaman hanya dalam jumlah yang mereka mampu untuk kehilangan sekiranya peminjam dana tidak dapat mengembalikan pinjaman.</p>
<p>Zidisha bukan lembaga keuangan, dan tidak bertanggung jawab untuk mengumpulkan pengembalian dana atau menjamin pengembalian dana yang diposting di website Zidisha. Zidisha bekerja dengan mitra lembaga keuangan local dan biro kredit yang bertanggung jawab untuk memeriksa sejarah piutang yang di posting oleh calon peminjam pada website Zidisha. Pendana berpartisipasi dalam pemberian pinjaman melalui Zidisha dengan resiko pendana itu sendiri, berdasarkan dengan penilaian mereka sendiri terhadap sejarah piutang calon peminjam yang diposting di website, dan surat kepercayaan yang dipublikasikan oleh mitra Zidisha yang memeriksa sejarah-sejarah piutang peminjam.</p>
<p>Pendana menerima resiko kehilangan seluruh atau sebagian pinjaman yang mereka berikan kepada peminjam Zidisha. Resiko termasuk tapi tidak terbatas akan ketidakstabilan politik dan ekonomi, fluktuasi mata uang, dan ketidakpastian yang merupakan bagian daripada ikhtiar kewirausahaan. </p>
<p>Dengan menggunakan website Zidisha website, dengan ini anda memahami dan menyepakati  hal-hal berikut:</p>
<p>1.  Zidisha bukan merupakan sebuah bank atau lembaga keuangan atau penasihat penanaman modal, atau makelar atau pedagang. Zidisha tidak membuat jaminan atau perwakilan bahwa dana yang dipinjamkan melalui websitenya akan dibayar kembali kepada pendana, meskipun pinjaman yang dibiayai oleh dana pendana dibayar kembali kepada Zidisha. Segala penyaluran uang oleh Zidisha kepada pendana adalah hadiah promosional yang ditawarkan semata-mata atas kebijaksanaan Zidisha.</p>
<p>2.  Zidisha bebas dan atau tidak bertanggung jawab atas segala ketidaktepatan informasi yang diposting pada websitenya, atau atas segala kerugian dan kerusakan yang dihasilkan dari informasi tersebut. Selain sejarah piutang dan kinerja pengembalian pinjaman, Zidisha atau lembaga keuangan setempat lainnya atau kredit biro yang mana Zidisha bekerja tidak memeriksa segala informasi yang peminjam pasang pada website Zidisha. Zidisha tidak bertanggung jawab untuk segala ketepatan informasi tersebut.
<p>3.  Pinjaman-pinjaman yang dipasang pada website untuk pembiayaan usaha melalui website Zidisha adalah tidak aman dan menanggung resiko yang tinggi akan tidak adanya pembayaran kembali dari peminjam. Zidisha tidak bertanggung jawab untuk segala kerugian keuangan sebagai hasil dari penggunaan website Zidisha.</p>
<p>4.  Pendana yang bertempat tinggal di luar Amerika Serikat hanya boleh menarik dana mereka dari akun Zidisha melalui PayPal. Jumlah penarikan yang dikreditkan kepada peminjam yang tidak tinggal di Amerika Serikat merupakan jumlah bersih dari biaya transaksi yang Paypal kurangi dari pemindahan-pemindahan dana ini. Zidisha tidak mengendalikan atau mendapat keuntungan dari biaya pemrosesan Paypal, yang berbeda dari Negara satu ke Negara lainnya. Adalah tanggung jawab pengguna-pengguna website untuk memperolah informasi akan biaya PayPal terkini sebelum menggugah dan menarik dana menggunakan website Zidisha. Pendana yang bertempat tinggal di luar Amerika Serikat yang tidak dapat menerima pemindahan dana dari PayPal tidak akan dapat menarik dana dari akun pendana mereka. </p>
<p>5.  Jumlah pinjaman tetap dalam mata uang setempat pada waktu pembaran. Fluktuasi kurs Mata uang dapat menyebabkan pengurangan terhadap nilai dolar peminjaman yang diberikan selama periode pembayaran, menyebabkan pendana untuk kehilangan uang meski pinjaman telah dikembalikan penuh.</p>
<p>6.  Dana-dana yang digugah pada akun pendana Zidisha tidak seharusnya dianggap sebagai pengurangan pajak kontribusi amal. Adalah tanggung jawab pengguna website untuk melaporkan dan membayar segala pajak yang berlaku dari pembayaran yang yang diterimDalam keadaan dimana pendana tidak memeriksa akun pendana nya dalam waktu satu tahun , Zidisha Inc. akan mencoba untuk menghubungi pendana tersebut di atas menggunakan alamat email yang terdaftar dalam akun pendananya. Apabila Zidisha Inc. tidak menerima tanggapan dari pendana dalam waktu satu bulan dari tanggal kontak pertama yang diupayakan, saldo dana pendana yang telah dikreditkan ke akun pendana tersebut akan secara automatis diubah sebagai sumbangan tidak terikat kepada Zidisha Inc., dan tidak akan lagi tersedia bagi pendana tersebut.  </p> 
<p>Persyaratan Penggunaan ini diatur oleh hukum Negara bagian Virginia, Amerika Serikat. Perjanjian ini akan tetap berpengaruh selama anda menggunakan website Zidisha, selama anda berpartisipasi dalam segala saldo pinjaman yang ada atau memiliki jumlah yang dikreditkan pada saldo yang anda danai dengan Zidisha.</p>

</p>
<p>Catatan penting:<br><br>
Zidisha adalah sebuah organisasi nirlaba yang ikut serta dalam mempermudahkan pinjaman microfinance untuk pengusaha berpendapatan rendah di Negara-negara berkembang. Tujuan utama Zidisha adalah untuk memberikan bantuan keangan dalam bentuk pinjaman pinjaman. Zidisha percaya bahwa contoh pinjamannya memelihara rasa tanggung jawab dan sukses untuk peminjam-peminjam yang mengembalikan pinjaman mereka. Tujuan utama pendana-pendana Zidisha dalam memberikan pinjaman dana adalah untuk membantu membiayai pengusaha-pengusaha tersebut, dan tidak untuk membuat investasi yang menguntungkan. Peminjaman dana kepada pengusaha-pengusaha melalui Zidisha melibatkan resiko kerugian akan pinjaman pokok anda. Sebagai tambahan, anda  mungkin tidak akan mendapatkan keuntungan dari segala pinjaman yang anda danai, meski pinjaman itu telah dibayar kembali oleh peminjam, sebagai hasil dari perubahan kurs mata uang dan unsur lainnya yang mempengaruhi nilai dana pokok dan pembayaran bunga oleh peminjam. Maka dari itu, anda tidak seharusnya meminjamkan uang lebih dari yang anda mampu untuk kehilangan.</p><br /><br />';
?>