<?php
$lang['about']['desc']='<b>A propos de nous</b><br />
<p> Zidisha est une organisation 501(c)(3), statut relatif aux associations à but non lucratif aux Etats-Unis, domiciliée dans l’état de Virginie.<p/><p/><p/>
<br /><b>Zidisha Team</b>

<p>JULIA KURNIA, Directrice</p>
<p> Julia a commencé son travail d’association entre entrepreneurs de pays pauvres et marchés internationaux de prêt entre particuliers en 2006, avec la cofondation du Fonds de Microfinance des Ecovillages du Sénégal. Il s’agit du plus ancien partenaire terrain de Kiva, ainsi que la première institution mondiale de microfinance, fondée grâce au capital rassemblé par des prêts entre particulier. Julia  a ensuite passé quatre mois au Kenya pour étudier les possibilités d’intégrer les opérations bancaires sur téléphone portable avec la microfinance, étude commanditée par MyC4, service de prêt de microfinance basé au Danemark. Ces expériences ont préparé le terrain pour la fondation de Zidisha en 2009. Julia travaille en tant qu’Analyste de Portefeuille à la Fondation des Etats-Unis pour le Développement de l’Afrique à Washington DC et possède un Master en Economie Internationale de l’Université George Washington. Vous pouvez contacter Julia à l’adresse <a href=\'mailto:julia@zidisha.org\'>julia@zidisha.org. </a>.</p></p><br />

<p>STEVE MONROE, Manager en Relations Clients au Sénégal
  <a href=\'http://dakardays.blogspot.com/\'>View Weblog</a> </p>
<p> Steve est jeune diplômé de l’Université de Stanford aux Etats-Unis, où il a étudié les Relations Internationales avec une spécialisation sur la zone du Moyen-Orient. Désireux de suspendre momentanément son parcours universitaire pour saisir l’opportunité d’apprendre et de promouvoir la microfinance, Steve a rejoint Zidisha en tant que Manager des Relations Client au Sénégal en automne 2010. Auparavant, Steve a travaillé en tant qu’assistant chercheur pour le Stanford’s Center for Democracy, Development and the Rule of Law (Centre de Stanford pour la Démocratie, le Développement et la Règle de Droit) et a mené des travaux récompensés sur les Comportements Démocratiques de Partis Islamiques des pays du Golfe Persique. Récemment reconverti au pouvoir et au potentiel de la microfinance, Steve est heureux de participer à la mission de Zidisha pour rendre la communauté d’entrepreneurs sénégalais plus autonomes et prospères. En 2011, Steve va intégrer la Fletcher’s School of Law and Diplomacy. Vous pouvez le contacter à l’adresse steve@zidisha.org.</a>.</p></p><br />

<p> LAUREN ROSENBAUM, Partenaire Communication      Voir blog
  <a href=\'http://ikosawa.wordpress.com/\'>View Weblog</a> </p>
<p> Lauren a travaillé en tant que première Manager en Relations Clients de Zidisha au Kenya durant l’été 2010 et finalise actuellement sa dernière année d’études à Dartmouth College où elle étudie les Relations Internationales et les Politiques Comparées et écrit pour le journal du campus. Durant l’hiver 2010, Lauren a reçu une bourse du Dartmouth\'s Dickey Center for International Understanding pour travailler en tant que stagiaire en communication au Crops Research Institute for the Semi-Arid Tropics (ICRISAT) à Nairobi au Kenya. Son travail avec ICRISAT impliquait la création de supports pédagogiques, la rencontre avec les industriels agro-alimentaires, des grossistes en céréales et des agents du Kenya Bureau of Standards (KEBS) à Nairobi, ainsi que l’animation d’ateliers avec des groupes de fermiers ruraux de l’ouest kenyan. Le travail de Lauren avec ICRISAT a renforcé son intérêt pour le développement international et sa volonté de travailler avec des habitants des milieux ruraux au Kenya. A son retour à Dartmouth au printemps, elle a posé sa candidature pour retourner au Kenya en tant que Manager en Relations Clients au Kenya et a effectivement reçu une bourse de l’Institut pour la Sécurité et la Technologie de Dartmouth. Vous pouvez consulter le blog de Lauren pour en savoir plus sur son travail avec les entrepreneurs ruraux au Kenya. Vous pouvez aussi la contacter directement à l’adresse lauren@zidisha.org.</a>.</p></p><br />

<p> YUKA NAGAI, Partenaire Communication      </p>
<p> Yuka termine ses études de marketing, communication et photographie à l’Emerson College de Boston dans le Massachussets. On lui a diagnostiqué un sévère cas de bougeotte en 2005, et elle a visité neuf pays depuis cette date. L’été dernier, elle a parcouru l’Amérique Centrale, ce qui lui a donné l’envie de travailler dans le développement économique international. Elle éprouve un intérêt particulier pour l’Amérique Latine et aimerait parler espagnol couramment. Elle a aussi participé à des projets internationaux dans le passé en Nouvelle Zélande, en Australie, à Vanuatu et au Paraguay, où elle a animé des cours de prévention sur le VIH/sida, des ateliers pédagogiques et de développement de la communauté. Elle souhaiterait dédier sa vie aux voyages, à la créativité et à faire le bien. Vous pouvez contacter Yuka à l’adresse  yuka@zidisha.org. </a>.</p></p><br />
<p>JOHN FAY, Trustee</p>
<p>John est impliqué dans la microfinance en Afrique depuis 2004, quand il a commence à développer l’organisation précédente qui est devenu <a href=\'http://www.sem-fund.org\' target=\'_blank\'>The Senegal Ecovillage Microfinance Fund</a> en 2006, cofondé par Nan Guslander, Julia Blue Kurnia et Boubacar Sarr. John en est aussi le président du conseil et le directeur, focalisé sur les stratégies et le développement de partenariats. John habite actuellement au Cap, en Afrique du Sud, où il fait un doctorat (PhD) à l’Université du Cap « Graduate School of Business », qui concerne en particulier les mécanismes et les motivations financières indispensables à l’Afrique pour réduire l’impact et s’adapter face aux changements climatiques. John est également conseiller international à mi-temps pour « Cardno Emerging Markets », qui s’occupe d’orienter les initiatives face aux changements climatiques. Auparavant, John a travaillé au « Cigna Healthcare », à la banque d’investissement FBR et au « Emerging Markets Group » (Groupes des marchés émergents), et a été un joueur professionnel de golf pendant six ans. Grâce à son travail avec le « SEM Fund » et avec le « Emerging Markets Group », il a été récompensé par le prix Truman en développement international de 2006. Il est diplomé d’un Bachelor en Histoire de l’Université de Duke et a obtenu un MBA de l’université de Johnson School à Cornell. Vous pouvez contacter John à l’adresse suivante : john@sem-fund.org.
 <a href=\'mailto:john@sem-fund.org\'>john@sem-fund.org</a>.</p></p> <br />

<p>DIANNE SCENT, Trustee</p>
<p>Dianne est un éditrice “freelance” dans l’Est Tennessee, où elle adore les montagnes de sa nouvelle maison. Sa carrière de 20 ans dans la presse inclut un travail en tant qu’éditeur académique et légal pour la « Wiley Cambridge University Press » et la « Transaction Publishers », ainsi que pour la maison d’édition chrétienne « Zondervan ». Elle est diplomée du « Hanover College » avec un BA en Anglais.  L’implication de Dianne dans la microfinance provient de l’appel de Micah sur sa vie : « Et qu’est que le Seigneur te demande à part faire la justice, partager la gentillesse, et marcher humblement aux côtés de Dieu ? ». Son inspiration inclut Mère Thérésa et Shane Claiborne. Vous pouvez contacter Dianne sur <a href=\'mailto:dscent@mindspring.com\'>dscent@mindspring.com</a>.</p></p><br />

<p>PRANJAL SRIVASTAVA, Chief Executive Officer, <a href=\'http://www.CodeFire.in\'>CodeFire Technologies Pvt. Ltd.</a></p>
<p>CodeFire Technologies est une compagnie de logiciel délocalisé en Inde. Nous adorons développer le challenge des applications informatiques et c’est comme ça que nous nous sommes associés à Zidisha.org. Nous apprécions la plateforme que Zidisha construit et nourrit, et comprenons que c’est un moyen efficace pour encourager de nouveaux entrepreneurs et pour leur fournir les fonds nécessaires afin qu’ils agrandissent leur business. CodeFire Technologies Pvt. Ltd., avec ses capacités techniques sous diverses perspectives a amélioré la technologie afin de fournir une plateforme solide à Zidisha.org. Comme le dit Pranjal Srivastava, PDG de CodeFire Technologies, « Nous nous sommes engagés à déployer le meilleur de la technologie pour Zidisha.org afin de fournir le plus haut niveau de service et de satisfaction dans la microfinance « pair-à-pair ». Nous sommes contents d’être partenaire de Zidisha.org à des fins technologiques et de soutenir l’initiative.» Vous pouvez contacter Pranjal sur  <a href=\'mailto:pranjal@codefire.in\'>pranjal@codefire.in</a>. </p></p>';
?>